import 'dart:async';
import 'dart:io';
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../models/detection_result.dart';
import '../services/detection_intelligence.dart';
import '../services/history_service.dart';
import '../services/language_service.dart';
import '../services/location_service.dart';
import '../services/ocr_service.dart';
import '../services/tts_service.dart';
import '../services/voice_command_service.dart';
import '../services/tflite_service.dart';

class LiveCameraScreen extends StatefulWidget{const LiveCameraScreen({super.key});@override State<LiveCameraScreen> createState()=>_LiveCameraScreenState();}
class _LiveCameraScreenState extends State<LiveCameraScreen>{
 CameraController? camera;Timer? timer;bool ready=false,processing=false,stopped=false,listening=false;String status='Starting camera';String last='';AppLanguage language=LanguageService.languages.first;
 final tts=TTSService(),voice=VoiceCommandService(),lang=LanguageService(),location=LocationService(),history=HistoryService(),ocr=OCRService(),intel=DetectionIntelligence();
 @override void initState(){super.initState();start();}
 Future<void> start()async{try{final saved=await lang.load();if(saved!=null)language=saved;final cams=await availableCameras();final back=cams.firstWhere((c)=>c.lensDirection==CameraLensDirection.back,orElse:()=>cams.first);camera=CameraController(back,ResolutionPreset.medium,enableAudio:false);await camera!.initialize();if(mounted)setState(()=>ready=true);if(saved==null)await chooseLanguage();else await speak('AI Signboard Reader is ready. Live scanning is on.');timer=Timer.periodic(const Duration(milliseconds:1800),(_)=>scan());}catch(e){setState(()=>status='Camera unavailable');await speak('Camera permission is required. Please allow camera access and restart the app.');}}
 Future<void> chooseLanguage()async{await speak('Welcome. Say English, Hindi, or Kannada.');final heard=await voice.listen(localeId:'en-US',timeout:const Duration(seconds:6));final code=LanguageService.detectCommand(heard??'')??'en';language=LanguageService.fromCode(code)??LanguageService.languages.first;await lang.save(language);await tts.setLanguage(language.speechLocale);await speak(language.name+' selected. Live scanning is starting.');}
 Future<void> scan()async{if(!ready||processing||stopped||listening||camera==null)return;processing=true;try{final shot=await camera!.takePicture();final file=File(shot.path);final raw=await TFLiteService().predictImage(file);if(raw.isEmpty)return;final list=<DetectionResult>[];for(final d in raw.take(3)){final text=d.confidence>=.45?await ocr.extractText(file,d.bbox,languageCode:language.code):'';list.add(DetectionResult(className:d.className,confidence:d.confidence,bbox:d.bbox,ocrText:text,classId:d.classId));}intel.setFrameSize(camera!.value.previewSize?.width.toInt()??416,camera!.value.previewSize?.height.toInt()??416);final ctx=intel.select(list);if(!intel.shouldAnnounce(ctx))return;final loc=await location.current();final speech=buildSpeech(ctx);await speak(speech);intel.markAnnounced(ctx);await HapticFeedback.mediumImpact();await history.add(DetectionHistoryEntry(label:ctx.detection.className,text:ctx.detection.ocrText,position:ctx.position.label,confidence:ctx.detection.confidence,latitude:loc?.latitude,longitude:loc?.longitude,timestamp:DateTime.now()));}catch(e){debugPrint('scan error: '+e.toString());}finally{processing=false;}}
 String buildSpeech(DetectionContext c){final d=c.detection;var s=d.className.replaceAll('_',' ')+' '+c.position.label;if(d.ocrText.isNotEmpty)s+=' . Text: '+d.ocrText;if(c.movement.isNotEmpty)s+=' . '+c.movement;if(d.className.contains('warning')||d.className.contains('construction')||d.className.contains('pedestrian_dont')||d.className.contains('stop'))s='Warning. '+s;return s+'.';}
 String localize(String s){if(language.code=='en')return s;if(language.code=='hi')return s.replaceAll('ahead','आगे').replaceAll('left','बाईं ओर').replaceAll('right','दाईं ओर').replaceAll('Warning','चेतावनी').replaceAll('Text:','पाठ:').replaceAll('getting closer','पास आ रहा है').replaceAll('moving farther','दूर जा रहा है');return s.replaceAll('ahead','ಮುಂದೆ').replaceAll('left','ಎಡಕ್ಕೆ').replaceAll('right','ಬಲಕ್ಕೆ').replaceAll('Warning','ಎಚ್ಚರಿಕೆ').replaceAll('Text:','ಪಠ್ಯ:').replaceAll('getting closer','ಹತ್ತಿರವಾಗುತ್ತಿದೆ').replaceAll('moving farther','ದೂರವಾಗುತ್ತಿದೆ');}
 Future<void>speak(String s)async{last=s;if(mounted)setState(()=>status=localize(s));await tts.speak(localize(s));}
 Future<void>commands()async{if(listening)return;listening=true;await tts.stop();await speak(language.code=='hi'?'आदेश बोलें।':language.code=='kn'?'ಆಜ್ಞೆಯನ್ನು ಹೇಳಿ.':'Say a command.');final r=await voice.listen(localeId:language.speechLocale);listening=false;if(r==null)return;await command(r);}
 Future<void>command(String raw)async{final s=LanguageService.normalize(raw);if(s.contains('stop')||s.contains('रुको')||s.contains('ನಿಲ್ಲಿಸು')){stopped=true;await speak('Scanning stopped.');}else if(s.contains('scan')||s.contains('continue')||s.contains('स्कैन')||s.contains('ಸ್ಕ್ಯಾನ್')){stopped=false;await speak('Scanning resumed.');}else if(s.contains('repeat')||s.contains('दोहर')||s.contains('ಮತ್ತೆ'))await speak(last.isEmpty?'Nothing to repeat.':last);else if(s.contains('help')||s.contains('मदद')||s.contains('ಸಹಾಯ'))await speak('Say scan, stop, repeat, change language, history, navigate, or help.');else if(s.contains('change language')||s.contains('भाषा')||s.contains('ಭಾಷೆ'))await chooseLanguage();else if(s.contains('history')||s.contains('इतिहास')||s.contains('ಇತಿಹಾಸ')){final h=await history.read();await speak(h.isEmpty?'No recent signs.':'There are '+h.length.toString()+' recent detections.');}else if(s.contains('navigate')||s.contains('दिशा')||s.contains('ನ್ಯಾವಿಗೇಟ್'))await speak('GPS context is available. Exact sign distance is not claimed unless it can be estimated reliably.');else await speak('I did not understand. Say help for commands.');}
 @override Widget build(BuildContext c){if(!ready||camera==null)return Scaffold(body:Center(child:Text(status)));return Scaffold(backgroundColor:Colors.black,body:Stack(children:[Positioned.fill(child:CameraPreview(camera!)),SafeArea(child:Column(children:[Align(alignment:Alignment.topLeft,child:Container(margin:const EdgeInsets.all(16),padding:const EdgeInsets.all(10),color:Colors.black87,child:Text(language.name))),const Spacer(),Semantics(liveRegion:true,child:Container(width:double.infinity,padding:const EdgeInsets.all(16),color:Colors.black87,child:Text(status,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)))),Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:ElevatedButton.icon(onPressed:commands,icon:const Icon(Icons.mic),label:const Text('Voice commands'),style:ElevatedButton.styleFrom(minimumSize:const Size(0,58)))),const SizedBox(width:10),IconButton.filled(onPressed:()=>command(stopped?'scan':'stop'),icon:Icon(stopped?Icons.play_arrow:Icons.stop),iconSize:30,padding:const EdgeInsets.all(14))]))]))]));}
 @override void dispose(){timer?.cancel();camera?.dispose();voice.stop();tts.stop();super.dispose();}
}
